# Generated by Django 3.2.16 on 2022-12-22 01:25

import app_modules.movies.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('runtime', models.PositiveIntegerField(verbose_name='Run Time')),
                ('language', models.CharField(max_length=50, verbose_name='Tag Line')),
                ('tagline', models.CharField(max_length=255, verbose_name='Tag Line')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('gender', models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE'), (3, 'TRANS'), (4, 'NON_BINARY')], default=app_modules.movies.models.Gender['MALE'], verbose_name='Gender')),
                ('dob', models.DateField(verbose_name='DOB')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
